### ISSUE TITLE
Issue with dark theme

### ISSUE THREAD

**Issue by mauro-ni** [viclafouch/mui-tel-input#101]
Hi, there seems to be an issue with dark theme.
Normal TextField render with proper colors, MuiTelInput use light mode colors also when in dark mode.

![Screenshot 2023-10-18 at 17 13 38](https://github.com/viclafouch/mui-tel-input/assets/1393996/1b5c3ace-4e5a-4eee-a04c-ada74ab7bb03)

Many thanks.

Mauro

**Comment by viclafouch** [comment]
Hello ! 

Could you please share a codesandbox for repro ?

Ty !
