### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by alextracy** [viclafouch/mui-tel-input#102]
**Nextjs version:** 13.5.6
**Nodejs version:** 20.8.1

**Error:** import { jsxs as _, jsx as p, Fragment as Fe } from "react/jsx-runtime";
^^^^^^
SyntaxError: Cannot use import statement outside a module

No error with version 4.0.0
This error only happens with version 4.0.1

**Comment by viclafouch** [comment]
Duplicated with https://github.com/viclafouch/mui-tel-input/issues/84
