### ISSUE TITLE
disableFormatting prop bugs typing in input value of +11

### ISSUE THREAD

**Issue by vparusheva** [viclafouch/mui-tel-input#106]
Version: mui-tel-input **4.0.1**
Scenario:
1. Open the code sandbox below https://codesandbox.io/s/mui-tel-input-forked-94wqzq
2. Delete the default code (+33)
3. Type in "1". "+1" is input. Try to type in another "1".
4. You should see "+11". Instead, the second "1" is not added. This works fine if disableFormatting is not added. This works fine with other digits (e.g. +2222, +3333, +1234 etc)

**Comment by viclafouch** [comment]
Fixed ! Ty ;)
