### ISSUE TITLE
Cannot find module 'mui-tel-input' or its corresponding type declarations

### ISSUE THREAD

**Issue by Victor1890** [viclafouch/mui-tel-input#109]
![image](https://github.com/viclafouch/mui-tel-input/assets/46900196/aa1dcf31-fcaf-454b-a892-c574a846ab3f)

Cannot find module 'mui-tel-input' or its corresponding type declarations.
This could be one of two things - either mui-tel-input doesn't exist on your file system, or I can't find any type declarations for it.

mui-tel-input: 4.0.1
next: 13.2.4
@mui/material: 5.11.3

**Comment by viclafouch** [comment]
Hello ! 

Could you please share a codesandbox for repro plz ?

**Comment by Victor1890** [comment]
False alarm, I had a problem with Next.js cache
