### ISSUE TITLE
it seems it can't support iOS 12.5, the  libphonenumber-js  it need Intl.DisplayNames

### ISSUE THREAD

**Issue by tianyingchun** [viclafouch/mui-tel-input#11]
it seems it can't support iOS 12.5, the  libphonenumber-js  it need Intl.DisplayNames

it try `react-phone-number-input` it works fine on 12.5,  and does this libararay support tree-sharking? it seems that the libphonenumber-js  is very big

**Comment by viclafouch** [comment]
Hello @tianyingchun !

IOS 12 represents 3% of the global IOS market, so I don't think a fix is necessary.

Concerning the library, yes it supports tree shaking.

**Comment by tianyingchun** [comment]
and then could you use `autocomplete` instead conuntry flag selector?

**Comment by viclafouch** [comment]
I don't understand what you mean by an autocomplete :/

**Comment by tianyingchun** [comment]
for country flag, it better allow us input search filter

**Comment by tianyingchun** [comment]
<img width="812" alt="image" src="https://user-images.githubusercontent.com/2833251/187577915-1e9950d4-2236-40db-b17d-15191679b028.png">
https://mui.com/material-ui/react-autocomplete/

**Comment by viclafouch** [comment]
Yes, it is on my roadmap :)
