### ISSUE TITLE
Feature request: Expose css selector to select flag

### ISSUE THREAD

**Issue by spicattutti** [viclafouch/mui-tel-input#116]
v5 made the flag images slightly bigger (`26x26px` instead of `20*20px`).

We'd like to keep the UI somewhat consistent. Fix would be to style the flag using the existing selector 
that is used internally (`MuiTelInput-Flag`)

<img width="444" alt="image" src="https://github.com/viclafouch/mui-tel-input/assets/107466292/4df56523-3f01-4662-b05c-04a05bb93b85">

Could the class name be exported as string constant, to have a fixed reference to the box so that consumers can safely style the flag, without the risk of the reference breaking in between version updates?

Just targeting any `img` within the component seems a little dangerous on the long run.

MUI helps in those cases by exporting class names, therefore my suggestion.

```
import { outlinedInputClasses } from "@mui/material/OutlinedInput";
```

**Comment by viclafouch** [comment]
Hello ! 

Not sure about the solution, please feel free to open a PR ;)
