### ISSUE TITLE
how to change the size of dropdown when open?

### ISSUE THREAD

**Issue by SinaMicrocis** [viclafouch/mui-tel-input#118]
I want to resize the dropdown when it opens. For example: the height should be 10rem
![Screenshot 2024-01-21 153717](https://github.com/viclafouch/mui-tel-input/assets/134995910/abc09ff3-003a-4d42-bc77-0a781f1c75e1)

**Comment by viclafouch** [comment]
Hello ! 

Use the CSS classes availables : https://viclafouch.github.io/mui-tel-input/docs/css/
