### ISSUE TITLE
Cannot read properties of undefined (reading 'search')

### ISSUE THREAD

**Issue by mrLuisFer** [viclafouch/mui-tel-input#12]
I am testing the MUI Phone libraries and in this I get the following error
<img width="974" alt="Captura de Pantalla 2022-08-31 a la(s) 21 15 46" src="https://user-images.githubusercontent.com/65029792/187818126-9afd3958-a6cb-4fa4-9492-c77ee3396ebc.png">

I have not yet put all the Props that I need but with the basic ones according to the Documentation
- [mui-tel-input/docs/react-hook-form](https://viclafouch.github.io/mui-tel-input/docs/react-hook-form/)
<img width="351" alt="Captura de Pantalla 2022-08-31 a la(s) 21 18 54" src="https://user-images.githubusercontent.com/65029792/187818273-6e11e8ce-2530-47fe-9e18-e84a8ac79065.png">

Node Version: v14.15.0

**Comment by viclafouch** [comment]
Hey @mrLuisFer !

Nice catch ! 

it's because the value is `undefined` or `null`. Let me add a security for that :)

**Comment by viclafouch** [comment]
Fixed ! You can now pass `undefined` as value.
