### ISSUE TITLE
Jest - SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by syanaputra** [viclafouch/mui-tel-input#123]
Hi, I'm having an issue running a unit test using `jest` with this `mui-tel-input` package.

Has anyone faced the same issue?

---

## Issue Details

**Version:** 5.0.0

**Issue:**

- Unable to run unit testing using `jest` with the following error:

```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { jsx as N, jsxs as H, Fragment as Fe } from "react/jsx-runtime";
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      15 |   lastName: string;
      16 |   telephone: string;
    > 17 |   mobile: string;
         |                      ^
      18 |   position: string;
      19 | };
      20 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.<anonymous> (src/features/myprofile/editprofileform/EditProfileForm.tsx:17:22)
      at Object.<anonymous> (src/features/myprofile/editprofileform/EditProfileForm.test.tsx:6:26)
```

**Project Details:**

- `next@14.1.0`
- `react@18.2.0`
- `jest@^29.6.4`
- `@emotion/cache@^11.11.0`
- `@emotion/react@^11.11.1`
- `@emotion/styled@^11.11.0`
- `@mui/icons-material@^5.14.11`
- `@mui/material@^5.14.11`
- `@mui/x-data-grid-pro@6.1.0`
- `@mui/x-date-pickers@6.1.0`

**Comment by viclafouch** [comment]
Duplicate with https://github.com/viclafouch/mui-tel-input/issues/89
