### ISSUE TITLE
Feature request: possibility to decorate country code prefix

### ISSUE THREAD

**Issue by bigkrp** [viclafouch/mui-tel-input#131]
If for some reason(business requirements) we don't need `+`(plus symbol) as a prefix for iso code, currently we haven't such an option.

Prefix is hardcoded.
https://github.com/viclafouch/mui-tel-input/blob/master/src/index.tsx#L183

**Comment by viclafouch** [comment]
Hello @bigkrp 

As it's a really rare use case, I think I will wait for more upvote from the community before working on this feature.

Hope you understand
