### ISSUE TITLE
Typo on the docs

### ISSUE THREAD

**Issue by Donivanes** [viclafouch/mui-tel-input#14]
Didn't know where to put this. It's just a typo on your documentation. Thanks you for your job on this library! 

<img width="864" alt="typo" src="https://user-images.githubusercontent.com/22077321/188441678-922d10f3-2a5f-4285-b316-4a9d0f7dbafc.png">

**Comment by viclafouch** [comment]
@Donivanes Thank you very much ! Fix and deployed ☺️
