### ISSUE TITLE
Some country flags bigger than others

### ISSUE THREAD

**Issue by ulysse0** [viclafouch/mui-tel-input#141]
Hi,

So basically I am using this lib like this:

```
<Grid item xs={12}>
    <FormControl sx={{ width: '100%', mt: 2}} variant="outlined">
        <MuiTelInput value={phoneNumber} onChange={setPhoneNumber} required defaultCountry="FR" label="Phone number" />
    </FormControl>
</Grid>
```

And there are 2 countries (Ascencion Island and Tristan Da Cunha) with a very large flag image. Any fix for this ?

![image](https://github.com/viclafouch/mui-tel-input/assets/114408862/282aabcc-8f24-444e-abb8-a87f2884bdd9)
![image](https://github.com/viclafouch/mui-tel-input/assets/114408862/1aad2c0d-7591-4333-b6fe-e3c7cbe499f1)

**Comment by viclafouch** [comment]
Hello ! 

Could you please share a codesandbox plz ? 

Victor
