### ISSUE TITLE
Flag not detected when typing Country Code +212

### ISSUE THREAD

**Issue by AchrafElhadi** [viclafouch/mui-tel-input#143]
When I write, for example, "+33," it detects the flag of the country "France." Similarly, when I write "+34," it detects the flag of Spain. However, when I write "+212," it doesn't detect the flag of Morocco. To have it detected, I have to select it from the list or write the phone number completely

**Comment by viclafouch** [comment]
This library is using libphonenumber-js for getting these informations, so I think you should set an issue there.
