### ISSUE TITLE
Country info is not correct.

### ISSUE THREAD

**Issue by rupam71** [viclafouch/mui-tel-input#144]
![image](https://github.com/viclafouch/mui-tel-input/assets/25828822/293cc2c6-4e2d-4b24-9673-7ff7281db6a6)

At first i was in Bangladesh. My Bangladesh info was correct.
And than I select Baharain. Now Baharain info is not correct. 

`{
    "value": "+9731687",
    "info": {
        "countryCallingCode": "880",
        "countryCode": "BH",
        "nationalNumber": "1687",
        "numberType": null,
        "numberValue": "+8801687",
        "reason": "country"
    }
}`

Baharain country code is ok.
but Baharain county calling code is not ok.

**Comment by PolkowskiA** [comment]
I have the same problem. I have noticed that when I use `disableFormatting` props the `MuiTelInputInfo.countryCallingCode` does not change - always stays at the current country code, only change of number triggers change of calling code.

**Comment by viclafouch** [comment]
Hello ! 

I need a repro with a codesandbox.

**Comment by rnsnceman** [comment]
https://github.com/user-attachments/assets/12319470-5adc-40f5-b3a7-028370f76920

**Comment by viclafouch** [comment]
Looks like it's an issue from `libphonenumber-js`, the lib that handles country for the user input :/
