### ISSUE TITLE
How is the country list ordered? 

### ISSUE THREAD

**Issue by wkerswell** [viclafouch/mui-tel-input#15]
I would expect to see the list in alphabetical order however it doesn't quite appear like that. 

![Screenshot 2022-09-21 at 12 00 44](https://user-images.githubusercontent.com/3217365/191487911-64db9411-e95b-4325-b5dc-9a26dccb452c.png)

**Comment by viclafouch** [comment]
Hey @wkerswell !

Very good catch ! Fixed in the last release: https://github.com/viclafouch/mui-tel-input/releases/tag/v2.0.2

Thank you ! 😘
