### ISSUE TITLE
Material UI tel input does not work in Safari browser versions 12, 13 and 14

### ISSUE THREAD

**Issue by olegyahont15** [viclafouch/mui-tel-input#150]
I constantly get this error:
 **_TypeError undefined is not a constructor (evaluating 'new Intl.DisplayNames(B,{type:"region"})')_**
 when I use Safari browser (versions 12, 13 and 14)
 Possibly it happens here - **_/node_modules/mui-tel-input/dist/mui-tel-input.es.js_**
   ```
try {
    return new Intl.DisplayNames(t, {
      type: "region"
    });
  } catch (n) {
    return L(n), new Intl.DisplayNames(pt, {
      type: "region"
    });
  }
}
const Bn = ({
```
Has anyone encountered problems with this library on older Safari browsers?

P.S. Also doesn't work on Chrome 80 and Chrome Mobile 74

**Comment by viclafouch** [comment]
This library does not support old browsers. Sorry.
