### ISSUE TITLE
Feature Request: Built-in placeholder to label functionality

### ISSUE THREAD

**Issue by rnsnceman** [viclafouch/mui-tel-input#152]
I was wondering if placeholder to label functionality is already a built-in feature? If it isn't, is there a way I could help implement it?

![placeholderlabelfunctionality](https://github.com/user-attachments/assets/568ea8c2-177e-4509-bb97-8f999180ecda)

**Comment by viclafouch** [comment]
Hello ! 

Nah, we force the label to shrink because it's not the same animation because of the flag position.
