### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module mui-tel-input React Typescript Jest 

### ISSUE THREAD

**Issue by shajjhusein** [viclafouch/mui-tel-input#153]
I see the below issue while run npm run test whi using the library mui-tel-input .
arelady i have added 
` transform: {
    '^.+\\.(ts|tsx)$': [
      'ts-jest',
      {
        tsconfig: 'tsconfig.test.json',
        isolatedModules: true,
      },
    ],
    '\\.js$': '<rootDir>/node_modules/babel-jest',
    '^.+\\.es\\.js$': '<rootDir>/node_modules/babel-jest',
  },
  transformIgnorePatterns: ['node_modules/(?!(mui-tel-input)/)'],`
  any recomndations ??
  below is my env 
  
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/093736e7-ce4d-41f2-a47a-31ce18e70334">

**Comment by viclafouch** [comment]
Did you follow all the recommendations ?
