### ISSUE TITLE
Type error using `MuiTelInputProps` after updating from MUI `v6.0.2` to `v6.1.0`

### ISSUE THREAD

**Issue by ruiaraujo012** [viclafouch/mui-tel-input#156]
Hello, as the title say, [here](https://codesandbox.io/p/sandbox/compassionate-hypatia-z9d2fm?from-embed=&workspaceId=025fd253-f4ce-4985-bf22-4fd22ef4e59b&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0z0l6zo00063b6lvmu5j53t%2522%252C%2522sizes%2522%253A%255B100%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0z0l6zo00023b6l42gc055r%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0z0l6zo00033b6lwwb3o1dq%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0z0l6zo00053b6ly195lrc8%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0z0l6zo00023b6l42gc055r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0z0l6zo00013b6lwo72v7c6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm0z0p1ne00023b6lw3ndba83%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A23%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A23%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FCustomMuiTelInput.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm0z0l6zo00023b6l42gc055r%2522%252C%2522activeTabId%2522%253A%2522cm0z0p1ne00023b6lw3ndba83%2522%257D%252C%2522cm0z0l6zo00053b6ly195lrc8%2522%253A%257B%2522id%2522%253A%2522cm0z0l6zo00053b6ly195lrc8%2522%252C%2522activeTabId%2522%253A%2522cm0z0lftx00123b6l5knn13zh%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0z0l6zo00043b6lw290nchr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm0z0lftx00123b6l5knn13zh%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm0z0l6zo00033b6lwwb3o1dq%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm0z0l6zo00033b6lwwb3o1dq%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) is the reproduction.

**Comment by ruiaraujo012** [comment]
@viclafouch Can you take a look at this please? This issue is preventing me from updating MUI in our codebase :/

Thank you.

**Comment by viclafouch** [comment]
Hello ! Fixed in https://github.com/viclafouch/mui-tel-input/releases/tag/v6.0.1 !

**Comment by ruiaraujo012** [comment]
Thank you
