### ISSUE TITLE
UK Telephone Codes do not work properly

### ISSUE THREAD

**Issue by SwarajRenghe** [viclafouch/mui-tel-input#16]
Thanks for the library once again!

When trying to enter a UK country code, the flag does not change, and the object does not recognise UK's `countryCode` or `countryCallingCode`.

### Steps to reproduce
1. Place cursor on the textfield, backspace on the default country code, and enter `+44`.

Configuration being used is the default codesandbox playground.

This behaviour does not seem to be happening on any other countries, but I have not tried all.

**Comment by SwarajRenghe** [comment]
Some more investigation revealed that this may be a limitation of the `libphonenumber-js`, which doesn't seem to be recognising a UK number unless it is fully entered (because the country code is shared between three other territories ["GB", "GG", "IM", "JE"]). I'm not sure what a good way to deal with this is - I would go with defaulting to (or providing a flag to default to) GB when +44 is encountered, and then fixing (if needed) the country flag when the entire number is entered. Would be curious to know how existing implementations deal with this.

**Comment by viclafouch** [comment]
Hey @SwarajRenghe ! 

I understand your concern, but this is how the `libphonenumber-js` library works...

For now, I'll leave this issue in its current state (opened) for now, and see if anyone has a better solution.

**Comment by kripple** [comment]
> Some more investigation revealed that this may be a limitation of the `libphonenumber-js`, which doesn't seem to be recognising a UK number unless it is fully entered (because the country code is shared between three other territories ["GB", "GG", "IM", "JE"]). I'm not sure what a good way to deal with this is - I would go with defaulting to (or providing a flag to default to) GB when +44 is encountered, and then fixing (if needed) the country flag when the entire number is entered. Would be curious to know how existing implementations deal with this.

In cases where the country flag is not selected and the user enters a non-unique country code, I think it makes sense to default to the largest territory. +44 -> GB, +1 -> US, and +39 -> IT, to name a few. The user is always able to select the country flag before entering a phone number and would be able to change the flag if the selected default was incorrect.
