### ISSUE TITLE
Feature Request: Add onBlur handler to return same information as onChange

### ISSUE THREAD

**Issue by astjohnpaycor** [viclafouch/mui-tel-input#160]
Are there any plans to add the `onBlur` handler to this and have it return the same extra information that the `onChange` handler does?

**Comment by viclafouch** [comment]
Helloo ! 

You would like the event, and, the informations ?

**Comment by astjohnpaycor** [comment]
@viclafouch Yes. Right now you can use the `onBlur` attribute as it would normally be used on an input field, but then you only have access to the event target value, and not the full information about the telephone number that the library provides when using the `onChange` handler. So, it would be nice if the component was enhanced to return the same exact information it would when you're using the latter handler.

**Comment by viclafouch** [comment]
Thanks. 

It has been done, but I will release it in a week. I'm waiting for any feedback/bugs from the last version I've just pushed an hour ago.

Thanks.

**Comment by astjohnpaycor** [comment]
Thank you!! <3

**Comment by viclafouch** [comment]
Oo so sorry, let me release this weekend ;)

**Comment by astjohnpaycor** [comment]
Hi there, sorry to bother you again, but any updates on this?

**Comment by viclafouch** [comment]
Hello ! WIll be released with React 19 soon ! Sorry for the delay !

**Comment by astjohnpaycor** [comment]
@viclafouch Is there any way to backport this to be a minor release on version 7? We can't upgrade to the latest version since we're not on React 19 yet, and this change was not dependent on React 19.
