### ISSUE TITLE
null Country Code Returned for Certain Countries

### ISSUE THREAD

**Issue by Suwetaa-Ramesh** [viclafouch/mui-tel-input#162]
I noticed that the **info.countryCode** returned by the onChange handler is sometimes null for certain countries, even when a valid phone number is provided. This behavior was observed specifically for countries like  **Guadeloupe (+590), Mayotte (+262), and Réunion (+262).**

![image](https://github.com/user-attachments/assets/3a70498d-0a4d-4d2d-9e0f-a811bcb1d6b0)

**Affected Countries:**

Guadeloupe (+590)
Mayotte (+262)
Réunion (+262)

**Additional Information:**

Library Version: ^6.0.1
React Version: ^18.2.0

**Comment by viclafouch** [comment]
This library is using `libphonenumber-js` for getting these informations, so I think you should set an issue there.
