### ISSUE TITLE
Limit max input per country

### ISSUE THREAD

**Issue by quad5** [viclafouch/mui-tel-input#168]
Currently user can enter more than 10 phone number digits. 

Could it be done in this library to limit the max number of digits a user can enter for each country?

v7.0.0
"@mui/material-nextjs": "^6.3.0"

![maxNumber](https://github.com/user-attachments/assets/96e4424c-7859-4178-9983-b411b13d55e0)

**Comment by viclafouch** [comment]
Nah, the library doesn't know how many "numbers" we need for each country. Sorry.
