### ISSUE TITLE
Passing invalid number to mui-tel-input does not display invalid number.

### ISSUE THREAD

**Issue by waleedarshad** [viclafouch/mui-tel-input#21]
Hi,

I am using mui-tel-input in my react app. input works fine when I add a number, either valid or invalid but if we have already saved the number coming from the API. It does not show those numbers in the mui-tel-input field.

Does the library support this on loading?

**Comment by viclafouch** [comment]
Hey, can you share a sandbox to be sure I understand plz ?

**Comment by waleedarshad** [comment]
@viclafouch see I am passing some value to MuitelInput. but the value  is not displaying and the field is empty

```
<MuiTelInput
              {...field}
              value="+132323232322323"
              inputRef={ref}
              inputProps={{ readOnly: readonly }}
              InputLabelProps={{ shrink: true }}
              error={!!errors.phone}
              forceCallingCode
              focusOnSelectCountry
              preferredCountries={["US"]}
              defaultCountry="US"
              variant="standard"
              {...commonProps("phone", "", "Phone", validation["phone"])}
            />
```
<img width="852" alt="Screen Shot 2022-10-15 at 11 48 02 AM" src="https://user-images.githubusercontent.com/5329697/195973414-59ee4625-51a2-497c-b5c6-1a95dfdeea0b.png">

**Comment by waleedarshad** [comment]
@viclafouch ?

**Comment by viclafouch** [comment]
FIxed in https://github.com/viclafouch/mui-tel-input/releases/tag/v2.0.4

Thanks for your patience. Please open a new issue if something is wrong again.

**Comment by waleedarshad** [comment]
Thanks @viclafouch
