### ISSUE TITLE
Empty default phone number shows no country flag

### ISSUE THREAD

**Issue by cowley05** [viclafouch/mui-tel-input#22]
Firstly great library!

I used it and wanted the default flag to be GB (i guess it doesn't matter which you want). In order to do that I tried having the value field set to `'+44'` I also tried `''` and a few other permutations of silly things I thought it may be. Using all of these results in the same issue of the flag being undefined and having the default greyed out flag symbol.

In the end I had to input a default phone number of `+44 7777 777777` and then this meant I had to have a validation rule to accommodate this etc. etc. Not to mention it being a complete hack around.

If there is another way of doing this it would be nice to know and maybe update the docs but...

It would be great to have a prop that allows me to show a default flag with empty phone number value eg:

```<MuiTelInput 
                     forceCallingCode
                     preferredCountries={['GB']}
                     onChange={handleChange}
                     value={''}
                     defaultCallingCode={'GB'}
        />```

and this could show the phone number field with a value of +44 and a flag of GB

**Comment by viclafouch** [comment]
Hey !

`defaultCallingCode` doesn't exist. Please check the documentation : https://viclafouch.github.io/mui-tel-input/

Maybe you need "defaultCountry" ?
