### ISSUE TITLE
React hook form implementation doesn't return error on load

### ISSUE THREAD

**Issue by waleedarshad** [viclafouch/mui-tel-input#23]
Here is a code snipped and screenshot attached, I am using react hook form implementation and when I edit phone number already saved in the system, It does not return error on load.

If I edit that same some then it make input field invalid but still empty message is returning```

```
export const PhoneInput = ({
  prefix,
  register,
  validation = { phone: true },
  readonly,
  errors,
  onChange,
  control,
}) => {
  return (
    <>
      <Controller
        name="phone"
        control={control}
        rules={{
          required: validation["phone"],
          validate: matchIsValidTel,
          pattern: {
            value: PHONE_REGEX,
            message: "Please enter a valid phone number",
          },
        }}
        render={({ field: { ref, ...field }, fieldState }) => {
          return (
            <MuiTelInput
              {...field}
              inputRef={ref}
              inputProps={{ readOnly: readonly }}
              InputLabelProps={{ shrink: true }}
              error={!!errors.phone}
              forceCallingCode
              focusOnSelectCountry
              preferredCountries={["US"]}
              defaultCountry="US"
              variant="standard"
              {...commonProps("phone", "", "Phone", validation["phone"])}
            />
          );
        }}
      />
      <ErrorInfo errors={errors} name="phone" prefix={prefix} />
    </>
  );
};
```
<img width="1789" alt="Screen Shot 2022-10-18 at 12 20 05 AM" src="https://user-images.githubusercontent.com/5329697/196265326-1e3027eb-1775-49d3-b178-7eee3d5efd70.png">

<img width="1766" alt="Screen Shot 2022-10-18 at 12 29 48 AM" src="https://user-images.githubusercontent.com/5329697/196265705-9fcc3ad0-f9a9-49ad-bf82-1a5c599b430d.png">

**Comment by viclafouch** [comment]
Hey ! 

I'm not sure it's an issue from 'mui-tel-input'. Here, there is no difference with the MUI `error` prop on a `TextField`. If the prop is `true`, then the TextField will be `red`. That's all. No more logic. 

So I think you have to find a solution with React Hook form on your side.

**Comment by waleedarshad** [comment]
Thanks @viclafouch , I was indeed react hook form issue and I am able to solve it myself.

Thanks for awesome supports. hats off
