### ISSUE TITLE
Issue loader webpack

### ISSUE THREAD

**Issue by Huynt-dev** [viclafouch/mui-tel-input#25]
Can you check this issue, I can't use it
![image](https://user-images.githubusercontent.com/41951421/199896310-c2c58e4a-721f-41cf-811a-ade5f0e82cb7.png)

Thanks for sharing, Looking forward to hearing from you.

**Comment by viclafouch** [comment]
Duplicated with https://github.com/viclafouch/mui-tel-input/issues/17
