### ISSUE TITLE
Padding off for filled variant (variant="filled")

### ISSUE THREAD

**Issue by daniel-j-h** [viclafouch/mui-tel-input#26]
Hey folks, I'm giving your library and try and need to style the phone input as a filled field.

What I see is there's a difference in padding between the default (non-filled) and the filled variant; see below

![mui-tel-input-filled](https://user-images.githubusercontent.com/527241/200565826-7f3717f3-9cda-4307-8a1a-657f1e7fe760.gif)

Is this an issue in mui-tel-input where we need to special case the filled variant or style it differently?

Here's how to reproduce: go e.g. to this example's code sandbox and add `variant="filled"`

https://viclafouch.github.io/mui-tel-input/docs/react-hook-form/

**Comment by viclafouch** [comment]
Hey @daniel-j-h 

Looks like there is no difference between the original TextField from MUI and the tel input :

<img width="547" alt="image" src="https://user-images.githubusercontent.com/23353836/200783463-6db026c5-edce-4a86-97b1-ea4ca75d0ca7.png">

**Comment by daniel-j-h** [comment]
Ah, you are right! There are two issues at play here
1. The filled variant has less padding at the bottom than the default
2. Labels and field content are displayed differently, with different padding

Here is an example, on the first look it seems off, but the first two are labels but for the phone input it's not a label.

![text-vs-phone](https://user-images.githubusercontent.com/527241/200798320-f9b0d3d5-71b0-45c6-9b27-1b4a276cee78.gif)

I think we can close here as not actionable. Thanks for following up here :bow:
