### ISSUE TITLE
Make calling code separate from phone input

### ISSUE THREAD

**Issue by tomtastico** [viclafouch/mui-tel-input#27]
Is there any way to make the calling code not just not editable, but actually not part of the input field at all, but let's say part of the flag button?

Something like this:

![image](https://user-images.githubusercontent.com/690217/200622766-1ed677a1-ff4f-4000-bda3-10f719ba77de.png)

**Comment by tomtastico** [comment]
@viclafouch I have decided to make a PR for this, hope you like it! It should not affect current functionality if not enabling the `splitCallingCode` prop.

It also fixes https://github.com/viclafouch/mui-tel-input/issues/24

**Comment by viclafouch** [comment]
Fixed in https://github.com/viclafouch/mui-tel-input/releases/tag/v2.1.0

Thanks for your contribution!
