### ISSUE TITLE
Demo breaks in v1.3.0

### ISSUE THREAD

**Issue by fontoful** [viclafouch/mui-tel-input#3]
Just wanted to raise a flag here. 

I tried accessing the demo https://codesandbox.io/s/mui-tel-input-p7b2jz

I had to downgrade to v1.1.0 in order to make it work and also had to downgrade React to v17, it would't work in v18. 

I'm thinking of using this library, should I use v1.1.0?

**Comment by viclafouch** [comment]
Hello @fontoful !

A new version has been released ! 

Everything works again in both React 17 and 18.

Thanks for the flag !
