### ISSUE TITLE
libphonenumber-js provides an option to get phone number type, could you add it as an export please?

### ISSUE THREAD

**Issue by badddams** [viclafouch/mui-tel-input#32]
Hi, firstly, **this is fantastic**, the best one I've found so far for material-UI, great work. 👏 

I could really do with being able to import some of the other options from libphonenumber-js. I could just import the library myself into my codebase but seeing as you already provide an option to import the check for **isValidNumber** function I wondered if you thought it would make sense to also include the phone number type check?

For context, this is useful for me to know when to send a text message and when not i.e. landline vs mobile.

**_P.S. Side note_**: I noticed that the documentation for the integration with react-hook-form is referring to **version 7** of react-hook-form but I use version 6, this took me a little while to figure out why it wouldn't work for me. Might be nice to specify this in case others run into the same problem 😊  other than that, great work!

**EDIT**: Thinking about it, it would make sense if the NumberType was passed back as part of the _MuiTelInputInfo_ from the onChange event

**Comment by badddams** [comment]
I added PR with this change 😊  - https://github.com/viclafouch/mui-tel-input/pull/33

**Comment by viclafouch** [comment]
Waiting for a little fix and I merge it ;)

**Comment by badddams** [comment]
Remove package-lock and pushed :)
