### ISSUE TITLE
Reduce bundle size by using flagcdn

### ISSUE THREAD

**Issue by JanStevens** [viclafouch/mui-tel-input#36]
Hi,

Instead of using inline SVG's (and increasing the bundle) you can also pull images directly from flag cdn (see: https://flagpedia.net/download/api).

For example: https://flagcdn.com/20x15/be.webp returns the Belgian flag in webp format.

Would you be open for a PR for this?

**Comment by tomtastico** [comment]
At least I would like to have this option - right now mui-tel-input is one of the biggest parts of our bundle :/ 
![image](https://user-images.githubusercontent.com/690217/206481749-a61f719a-bc69-4e49-99b3-1507c77c912d.png)

**Comment by viclafouch** [comment]
Hey ! Will check asap ! Thanks for pointing the issue !

**Comment by viclafouch** [comment]
Fixed in https://github.com/viclafouch/mui-tel-input/releases/tag/v3.0.0 ! 

Thanks a lot !

**Comment by daniel-j-h** [comment]
Hey folks I just wanted to leave a comment here that this change might be problematic for some of your users for the following reasons
1. We don't control the images and what the server returns now or in the future breaking this package
2. We don't control funding, uptime, or SLAs for the 3rd party server and it might go down now or in the future breaking this package
3. Sending our user's IP addresses to this 3rd party is something we might not be allowed to do or should do

Therefore I'm asking you to re-consider making 3rd party requests in behalf of your users in favor of bundling the icons with this package.

**Comment by daniel-j-h** [comment]
Sure, optional makes sense, then folks can bundle their own flag icons.

Maybe it makes sense to split the package into two if you are so concerned about size
1. one with the icons for the tel input components
2. one with the tel input components alone and no icons

similar to how material ui does it https://mui.com/material-ui/material-icons/
