### ISSUE TITLE
Overriding styles for Countries Menu

### ISSUE THREAD

**Issue by hectorserranozen** [viclafouch/mui-tel-input#4]
This could completely be just me misusing Material overriding approaches but it looks like you can only override styles that are part TextField component and not the ones that come from the Menu, e.g:

.MuiTelInput-Menu
.MuiTelInput-MenuItem

And the rest of Menu-derived classNames. I believe this is because in the actual HTML, these are not children of the main Mui Tel Input component and since they're not children they don't even inherit any styling you may be passing to it. 

Here's how I'm doing the overriding which works for TextField overrides but not for Menu overrides:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/103968140/177029448-8080dc1d-12b6-432b-8251-06e02ea54f04.png">

Please consider providing an example of how you'd override the predefined styles.

**Comment by viclafouch** [comment]
Hello @hectorserranozen !

You have differents ways to style the `Menu` component and the children.

As u said, the `Menu` and the list inside are not child of the TextField because of the [createPortal](https://reactjs.org/docs/react-dom.html#createportal) API.

So, here how you can handle your issue :

## Option 1 : use traditional CSS 

```css
.MuiTelInput-Menu .MuiTelInput-MenuItem {
  background-color: yellow;
}
```

```js
import  './styles.css'

export const MyComponent = () => {
   return <MuiTelInput defaultCountry="FR" value={value} onChange={handleChange} />
}
```

## Option 2 : use the `sx` props

```js
export const MyComponent = () => {
   return (
       <MuiTelInput 
          defaultCountry="FR" 
          value={value} 
          onChange={handleChange} 
          MenuProps={{ sx: { backgroundColor: 'red'  }}} 
       />
   )
}
```

## Option 3 : use a styled component instead of `Paper`

```js
import { styled } from '@mui/material/styles'

const PaperComponent = styled(Paper)(({theme}) => {
  return {
    backgroundColor: 'red',

    '.MuiTelInput-MenuItem': {
      backgroundColor: theme.palette.primary.main
    }
  }
})

export const MyComponent = () => {
   return (
       <MuiTelInput 
          defaultCountry="FR" 
          value={value} 
          onChange={handleChange} 
          MenuProps={{
            PaperProps: {
              // @ts-ignore (if you use TypeScript)
              as: PaperComponent
            }
          }}
      />
   )
}
```

I hope this helps ! 😊

**Comment by hectorserranozen** [comment]
Hello @viclafouch , 

It's pretty thoughtful of you to include these proposed solutions for styling the Menu. 

As matter of fact, I was already taking the globalcss route that was suggested in the current documentation but for some reason it was getting injected late (I presume) as the styles wouldn't work on the first render, they'd only get applied when I was actively modifying the GlobalCssPhoneInput.css file and the Hot module replacement was doing its job. 

That was the only time when the overrides would apply. 

I'll go ahead and try out the other two proposed solutions, I'm sure they'll get the job done for me 🥳.

I've been pushing for this lib to be used at my job. 

I'll give this a go and will update this thread so it can serve as documentation/reference for other users of this great component you've created. 🎩 off to you!!! 👏🏻

**Comment by viclafouch** [comment]
Hey @hectorserranozen 

Humm that required a lot of time. Maybe when more people would up vote this issue, i will double check for that.

Thanks

**Comment by hectorserranozen** [comment]
Hey @viclafouch

That sounds good. I'm very happy how far along I got with the styles overriding and feel like I've learned a ton of tricks and good practices after checking out your repo. 

You're really killing it man, your code is a breath of fresh air!
