### ISSUE TITLE
Disable formatting only in onChange call

### ISSUE THREAD

**Issue by LotemAm** [viclafouch/mui-tel-input#42]
First of all, thanks for this great library!

It would be great to have an option to only disable formatting for the value itself, and not the visual component. Currently to have this feature I do quite an ugly hack

``` js
onChange={(value, info) => formik.handleChange('phone')(info.numberValue || '')}
```

**Comment by viclafouch** [comment]
I leave the question open and check if the community agrees with it..

**Comment by brandoningli** [comment]
I'm starting to implement this field in my project, and would love this feature. My end users would appreciate seeing the formatted version, but I need the unformatted version in the data.
