### ISSUE TITLE
FlagList menu improvement: sticky headers

### ISSUE THREAD

**Issue by mauro-ni** [viclafouch/mui-tel-input#48]
Hi, many thanks for this great library.
Would it be possible to separate preferred countries from others adding sticky sub headers to the list?
[https://mui.com/material-ui/react-list/#sticky-subheader](https://mui.com/material-ui/react-list/#sticky-subheader)

Many thanks,
Mauro

**Comment by viclafouch** [comment]
Hello !

Thank you for your feedback ! 

However, I don't think it's a good idea to keep the preferred countries in the viewport if the user scrolls down, as this suggests that he is not interested in those countries and it would not be useful to sticky them.

**Comment by viclafouch** [comment]
What do you suggest for the wording for these headers ?

**Comment by mauro-ni** [comment]
@viclafouch according to your API, I would use:

- Preferred countries
- Other countries

I would use headers only when preferredCountries is specified.

What do you think?

Many thanks,
Mauro

**Comment by viclafouch** [comment]
Humm why not yes ! 

I let

**Comment by mauro-ni** [comment]
@viclafouch ok, thank you!

**Comment by mauro-ni** [comment]
@viclafouch the fact that you closed this issue means that it won't be implemented?

Mauro

**Comment by viclafouch** [comment]
Nah sorry bro
