### ISSUE TITLE
Search Country not working in react Typescript

### ISSUE THREAD

**Issue by tgoswami19** [viclafouch/mui-tel-input#49]
By pressing alphabet, Search Country is not working in react Typescript. I used mui-tel-input for react with typescript. But when press a letter, the country not search.

**Comment by viclafouch** [comment]
Hello !

What do you mean by Search Country ??

**Comment by tgoswami19** [comment]
Search Country means, once I open the country list and type K, it will filtered the list and select the country which starts with K. Just like type search.

**Comment by viclafouch** [comment]
For me it's working :/

**Comment by tgoswami19** [comment]
Can you share the code insight please? Because I am using Typescript and its not working at all.

**Comment by viclafouch** [comment]
I really don't understand why you mention TypeScript, and why this code with a Tooltip.. Sorry miss too much information here.

**Comment by tgoswami19** [comment]
As I am using Typescript, thus I feel some functionality may not work with typescript and tooltip is require here thus I used this. Is tooltip restrict the search functionality?

**Comment by tgoswami19** [comment]
> I really don't understand why you mention TypeScript, and why this code with a Tooltip.. Sorry miss too much information here.

Using tooltip is it not work?
