### ISSUE TITLE
onChange prop won't work with Formik

### ISSUE THREAD

**Issue by SuiCxDe007** [viclafouch/mui-tel-input#50]
When using with [Formik](https://formik.org), we need to set the `onChange` prop to `formik.handleChange` since it will be handled via formik. However, when it's set in `MuiTelInput`, component values are not being updated as a result of following error.

        <MuiTelInput label="Phone No"
                                 required
                                 className="text-input"
                                 onChange={formik.handleChange}
                                 value={formik.phoneNo}
                                 name="phoneNo"
                                 id="phoneNo"/>

`Type {(e: React.ChangeEvent<any>): void, <T_1=string | React.ChangeEvent<any>>(field: React.ChangeEvent<any>): void} is not assignable to type (value: string, info: MuiTelInputInfo) => void`

However the issue can be fixed  by adding a `handleChange` method instead of using formik's handleChange method directly and calling the formik's handleChange method inside it as follows.
This leads to having to add a additional state to maintain.

    const handleTelNoChange = (newValue) => {
        setTelNo(newValue)
        formik.setFieldValue("phoneNo",newValue)
    }

**Comment by ja153903** [comment]
I'm not completely sure that this is an issue.

What's stopping you from doing something like

```typescript
<MuiTelInput
  onChange={() => {
  })
```

**Comment by ja153903** [comment]
I'm sure like most form-related libraries, you'll have access to the value via something like `formik.values.phoneNo`

I don't think you need additional state here. So implementing your handler as

```typescript
const handleTelNoChange = (newValue) => {
  formik.setFieldValue("phoneNo", newValue)
}
```

should be enough to update your state as long as you're actually using `formik.values.phoneNo` to render the phone number.

I also don't think this is really an issue. We're told that the `onChange` prop requires a callback with the above signature that you encountered in your error message. It's really up to us to integrate form libraries around that signature.
