### ISSUE TITLE
Input doesnt work with formik & yup, it's always disabled

### ISSUE THREAD

**Issue by BennyAlex** [viclafouch/mui-tel-input#51]
I try to use the phone input in a formik form, but it's permanently disabled and selecting a country doesnt work either:
![image](https://user-images.githubusercontent.com/17402724/219532764-2ccb09c6-cfa6-4bed-9949-07fa7dabfc5d.png)

          <MuiTelInput
            label='Phone'
            name='phone'
            placeholder='+491714883339'
            value={formik.values.phone}
            onChange={formik.handleChange}
            error={formik.touched.phone && Boolean(formik.errors.phone)}
            helperText={formik.touched.phone && formik.errors.phone}
            flagSize='medium'
          />

**Comment by viclafouch** [comment]
Hello ! 

Could you please share a sandbox with a repro.

Thanks

**Comment by BennyAlex** [comment]
@viclafouch 
here you go: https://codesandbox.io/s/cranky-benz-18dcbo?file=/index.js

**Comment by viclafouch** [comment]
Where is the Mui tel component ?

**Comment by viclafouch** [comment]
See https://github.com/viclafouch/mui-tel-input/issues/50
