### ISSUE TITLE
Feature Request: Does not allow more digits than the mask

### ISSUE THREAD

**Issue by iagoleao** [viclafouch/mui-tel-input#56]
Is it possible block for user not write more digits than the mask. It will avoid lost the mask when users write more digits the allowed to selected country.

**Comment by viclafouch** [comment]
Hello ! 

Looks like the lib https://gitlab.com/catamphetamine/libphonenumber-js doesn't provide any way to get the mask of the current country

**Comment by avele** [comment]
Hi @viclafouch! I think you can use `validatePhoneNumberLength` from `libphonenumber-js` to restrict input length.
