### ISSUE TITLE
useRef Error

### ISSUE THREAD

**Issue by mjth** [viclafouch/mui-tel-input#6]
I'm trying to implement this library with React 18 on NextJS 12.1,

I'm getting the following (very non-descript) useRef error when using just the very basic settings. I've tried to rollback to previous versions, and it doesn't seem like a new bug. Any idea what could be causing the issue?

`
        <MuiTelInput value={""} onChange={(val) => {}} />
`

![image](https://user-images.githubusercontent.com/3614846/178130325-9108a326-90b7-4893-8101-ae69874bfd7d.png)

**Comment by viclafouch** [comment]
Hey @mjth !

Looks like "React" is not defined. Doesn't seem to be an issue from the library.

Or maybe you have an example to show ?

**Comment by waleed-salama** [comment]
Hi,
I get the same error, with react-app and next-app. Next is more descriptive, but still not helpful.
I forked the repo, and cloned onto my computer. Then I npm install -> npm build -> npm link. After that, I linked mui-tel-input into a new CRA and a new create-next-app. Both of them fire an unhandled exception in the library code, seems to be in line 64 in index.tsx:

```
64  |    const textFieldRef = React.useRef<HTMLDivElement>(null)
```

I have used the library with no problems when npm installing it into my project. But I am now trying to contribute to the library by fulfilling one of the feature requests. I am new to working on libraries though. If anyone can help with this, I can continue to contribute to this library.

```
const [value, setValue] = React.useState("");
const telRef = React.useRef(null);
...
      <MuiTelInput
        ref={telRef} // Passing a ref or not makes no difference.
        label="Phone Number"
        value={value}
        onChange={setValue}
      />
```

Here is the error that shows up in the browser:

Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'useRef')

Source
Object.useRef
../mui-tel-input/node_modules/react/cjs/react.development.js (1630:0)
../mui-tel-input/dist/mui-tel-input.es.js (3874:15) @ eval

```
  3872 |   flagSize: Z = "small",
  3873 |   ...f
> 3874 | } = t, x = p.useRef(null), [O, D] = p.useState(null), E = e ? En(i) : i;
       |           ^
  3875 | zn(t);
  3876 | const { onInputChange: N, onCountryChange: nn, inputRef: R, isoCode: z, inputValue: Rt } = Xi({
  3877 |   forceCallingCode: e,
```
Call Stack
renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js (16305:0)
updateForwardRef
node_modules/react-dom/cjs/react-dom.development.js (19226:0)
beginWork
node_modules/react-dom/cjs/react-dom.development.js (21636:0)
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js (4164:0)
Object.invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js (4213:0)
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js (4277:0)
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js (27451:0)
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js (26557:0)
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js (26466:0)
renderRootSync
node_modules/react-dom/cjs/react-dom.development.js (26434:0)
performConcurrentWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js (25738:0)
workLoop
node_modules/scheduler/cjs/scheduler.development.js (266:0)
flushWork
node_modules/scheduler/cjs/scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
node_modules/scheduler/cjs/scheduler.development.js (533:0)
