### ISSUE TITLE
Restrict phone length

### ISSUE THREAD

**Issue by avele** [viclafouch/mui-tel-input#60]
After selecting or typing the country code, it is possible to input an arbitrary number of symbols. It would be great if the component had a prop to restrict the number of symbols in the telephone number according to the selected country's standards.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/34437766/225401492-e17a8e4a-08b2-47d2-ba1d-87b426e22dca.png">

**Comment by viclafouch** [comment]
Duplicated of https://github.com/viclafouch/mui-tel-input/issues/56
