### ISSUE TITLE
Javascript default parameters: Support

### ISSUE THREAD

**Issue by shawn1130** [viclafouch/mui-tel-input#63]
Getting the follow warning in the dev environment:

`Warning: we: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

seems like a easy fix to migrate `defaultProps` --> default parameters

**Comment by viclafouch** [comment]
Hey ! 

Thanks for the catch !

Fixed in https://github.com/viclafouch/mui-tel-input/releases/tag/v3.1.2
