### ISSUE TITLE
TypeScript typings not included in published NPM bundle

### ISSUE THREAD

**Issue by butterflyhug** [viclafouch/mui-tel-input#64]
The documentation says that typings are provided, and `package.json` refers to `./dist/index.d.ts` for type definitions, and running `npm run build` on a copy of this repository does generate that file... but the published NPM package [does not include that file](https://www.npmjs.com/package/mui-tel-input?activeTab=code), at least not in the current version (v3.1.2).

**Comment by viclafouch** [comment]
Hey ! 

Thanks for the catch, I really don't know what happened with the last build...
New version released with the correct ones :)

ty
