### ISSUE TITLE
Feature Request: Add optional clear button 

### ISSUE THREAD

**Issue by BennyAlex** [viclafouch/mui-tel-input#65]
Hey, I think it would be great to have a option for showing a clear button, similary to the MUI autocomplete clear.

Here is an example with a date input:
https://codesandbox.io/s/material-ui-pickers-usage-demo-2vnf5?file=/src/App.jsx

Best to use an svg clear icon, because MUI is also useable without material icons installed

**Comment by viclafouch** [comment]
Hello @BennyAlex 

Open for a PR 🥹
