### ISSUE TITLE
Limit number of visible options

### ISSUE THREAD

**Issue by SwarajRenghe** [viclafouch/mui-tel-input#7]
Hi! Thanks for the library - super helpful! 

Just a quick question - I'm looking for a way to only show a limited number of options, maybe 10 at a time, and have the user scroll to see more. It would also be great if the number of options visible could be dynamic, and depend on the size of the screen. Any ideas would be much appreciated!

**Comment by viclafouch** [comment]
Hello @SwarajRenghe ! 

Here, you ask for an infinite scroll, but for accessibility reason, I will not do that.
What I can purpose, is to have a search field inside above the list options. And to have 2 additional `props` : 

* enableSearchOptions
* maxOptionsVisible

What do you think ?

**Comment by SwarajRenghe** [comment]
`maxOptionsVisible` sounds exactly like something I was looking for, and the search bar is also a great idea. Do let me know if I can help in development

**Comment by viclafouch** [comment]
But, remember that you can add style to the Menu component thanks to the `sx` prop : 

```jsx
<MuiTelInput
      value={value}
      onChange={handleChange}
      MenuProps={{
        sx: {
          maxHeight: 200
        }
      }}
    />
```

<img width="461" alt="image" src="https://user-images.githubusercontent.com/23353836/178709491-baf48dcf-81bc-458e-a0ba-729a29bce950.png">
