### ISSUE TITLE
Giving ERROR: "IconButton" not defined

### ISSUE THREAD

**Issue by arijit-tweb** [viclafouch/mui-tel-input#72]
![image](https://github.com/viclafouch/mui-tel-input/assets/103941380/2ebb5438-305f-471b-aea5-12f5b54c7066)
I've  attached an image of the exact error message. Kindly look into it. Error occurred after installing the package on my project.

**Comment by viclafouch** [comment]
Hello ! 

You have to install `@mui/material` first.

```
npm install @mui/material @emotion/react @emotion/styled
```
