### ISSUE TITLE
Could not works for `canada` , `+1`

### ISSUE THREAD

**Issue by tianyingchun** [viclafouch/mui-tel-input#8]
https://codesandbox.io/s/mui-tel-input-p7b2jz?file=/src/App.js

1. choose `canada`/`us` +1 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/2833251/182736588-3ec4f47c-aa53-43cd-a43a-78e00478dad4.png">
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/2833251/182745857-33da980e-5cc4-4916-822f-061e5d2a7269.png">

2. typings any number  like ` (225) 588-8634`
<img width="408" alt="image" src="https://user-images.githubusercontent.com/2833251/182736609-f0945e82-7b96-47d9-a8ab-e8593adc17c7.png">

it seems that `+1` has some bugs here ?

**BTW please allow us filter while choose dropdown countries (MUI select control like)**

**Comment by viclafouch** [comment]
Hello @tianyingchun 

I followed your steps and I have the good result : 

<img width="418" alt="image" src="https://user-images.githubusercontent.com/23353836/183266265-c082e436-0fd0-45d0-b485-f5574b52525a.png">

**Comment by tianyingchun** [comment]
OH basically it seems give us input mistake feelling. please see

if we want to input phone number `407 590 8240` +1

1. we choose country `unitedState` it show. 
<img width="329" alt="image" src="https://user-images.githubusercontent.com/2833251/183291935-e1cc6277-3cf5-4e01-b16a-1d094a7038e4.png">
that's fine
2.  but while we input `407......` it will show us 

<img width="347" alt="image" src="https://user-images.githubusercontent.com/2833251/183291965-5ea87b21-4b3e-4951-b2c9-96102b1ac83f.png">

i think +1 country image should not changing while we typing input number, most people will feel there are some wrong ?

**Comment by tianyingchun** [comment]
BTW it should support area code is better like `+1 (704) 977-1657`

**Comment by viclafouch** [comment]
> i think +1 country image should not changing while we typing input number, most people will feel there are some wrong ?

You're right, let me fix that ASAP :)

> BTW it should support area code is better like `+1 (704) 977-1657`. ===>`(704)`

The value argument of onChange(value) function will be the parsed phone number in [E.164](https://en.wikipedia.org/wiki/E.164) format. For example, if a user chooses "United States" and enters (213) 373-4253 in the input field then onChange(value) will be called with value being "+12133734253".

**Comment by tianyingchun** [comment]
good news, when it will be release? waiting :)

**Comment by viclafouch** [comment]
I cannot give you a date sorry ^^

If you want to have the fix very very fast, you can submit a PR ! I'll take a look at it when I get back from vacation.

**Comment by tianyingchun** [comment]
:) waiting you fix & relase 👍

**Comment by AvidDesigner** [comment]
Hey this is happening for Aus code as well. +91. Can you please give a solution for this?

<img width="1440" alt="Screenshot 2022-09-21 at 1 50 07 PM" src="https://user-images.githubusercontent.com/85363318/191453424-a1611316-ff12-4615-809a-b907e3a2b0c2.png">
<img width="1440" alt="Screenshot 2022-09-21 at 1 50 15 PM" src="https://user-images.githubusercontent.com/85363318/191453480-519ab9ee-199d-43da-b8ad-28795975d386.png">

**Comment by viclafouch** [comment]
Hey ! I could not reproduce with the last version. Please open a new issue with a sandbox example. Thanks :)
