### ISSUE TITLE
Feature Request: Add option to enter the extension in the input

### ISSUE THREAD

**Issue by bryanjtc** [viclafouch/mui-tel-input#85]
What I would like is a second input field for the extension or allow typing ; and the extension.  This would also show the extension if there is one one the field because it does not show it now.  Could have a prop for allowExtension (true) by default which would show the extension field.  another prop for extensionDelimiter (x) by default.  This would be put into the value returned.

**Comment by viclafouch** [comment]
Hello ! 

Don't hesitate to open a PR !
