### ISSUE TITLE
Using setValue() from React Hook Form still triggers formatting despite disableFormatting is true

### ISSUE THREAD

**Issue by BoreasHe** [viclafouch/mui-tel-input#87]
### Minimal Reproducible Example
https://codesandbox.io/s/xenodochial-noyce-kgqr7l?file=/src/App.js:926-943

Note: I used the example from https://viclafouch.github.io/mui-tel-input/docs/react-hook-form/ and added some lines.

### Steps to Reproduce
1. Check that the `disableFormatting` prop is true in `MuiTelInput` component.
2. Try to type something inside the input box. The `disableFormatting` should work as intended.
3. Click the "Set Value!" button. Now you can see the 8-digit tel no. is separated by a space character.
4. The error message indicates that the input is invalid.

**Comment by viclafouch** [comment]
Hey ! 

It will be fixed in the next release ! 

Thanks @BoreasHe :))

**Comment by 000xuandu** [comment]
Hey @viclafouch 
I am facing this error also.
Is there any way to fix this error without upgrading ReactJs to v18?

**Comment by viclafouch** [comment]
Hello ! 

Nah, React 17 is not compatible anymore

**Comment by deepanAppycodes** [comment]
I am getting an error when using mui-tel-input with react hook form. It says Mn is not defined.
![image](https://github.com/viclafouch/mui-tel-input/assets/141302007/0a98af48-4bc7-4cad-8232-3ebb5f7f0623)

**Comment by viclafouch** [comment]
Please create a new issue with a codesandbox.
