### ISSUE TITLE
MuiTelInput Not Working: Country Flag Not Displaying and Text Field Uneditable

### ISSUE THREAD

**Issue by ADHIL007** [viclafouch/mui-tel-input#90]
**#I'm currently experiencing an issue with the MuiTelInput component from the Material-UI library. The MuiTelInput component is not working as expected. Two main problems are evident:**

1.**Country Flag Not Displaying:**
The country flag associated with the selected phone number country code is not showing up in the MuiTelInput component.

2.**Uneditable Text Field:**
Additionally, I'm unable to type in the text field of the MuiTelInput component. It appears to be uneditable.

![image](https://github.com/viclafouch/mui-tel-input/assets/56949215/180e0c90-5767-445b-83f8-276c3e91e5f5)

**Comment by viclafouch** [comment]
Hello ! 

Could you please share a codesanbox plz ?

**Comment by ADHIL007** [comment]
> Hello !
> 
> Could you please share a codesanbox plz ?

Apologies for my inquiry, but I'm relatively new to this field. I've written the code in VS Code. Should I share the entire code or just the component?

**Comment by viclafouch** [comment]
just the component :)

**Comment by fadiramzi** [comment]
Some issue Here!, any solution please
