### ISSUE TITLE
Possibility to have optional phone field with validation

### ISSUE THREAD

**Issue by ogflow** [viclafouch/mui-tel-input#91]
I am trying to set up a form with optional phone number, but yet with validation and preselected country code. Right now these options are conflicting with each other.

Would be nice to have some attribute controlling this :)

**Comment by viclafouch** [comment]
Not sure to understand what you mean by saying "options are conflicting"

**Comment by jannnik** [comment]
When using react-hook-form, the `defaultCountry` triggers `onChange`, which makes it difficult to implement the validation properly, since the phone field will be prefilled with a country code then and not be empty anymore. 

I solved it with this code: 

```
  const { countryCode } = useCountryCode();
  const {
    field: { ref: fieldRef, value, ...fieldProps },
    fieldState: { error, isTouched }
  } = useController({
    name: 'phoneNumber',
    rules: {
      validate: value => {
        if (!isTouched) return true; // <--- note this!
        return matchIsValidTel(value);
      }
    }
  });
  return (
    <MuiTelInput
      {...fieldProps}
      value={value ?? ''}
      inputRef={fieldRef}
      defaultCountry={countryCode}
```
