### ISSUE TITLE
Flag Mismatch When Switching Between Turkey and Kazakhstan

### ISSUE THREAD

**Issue by mkontik** [viclafouch/mui-tel-input#92]
Description:

There is an issue with flag display when switching between Turkey and Kazakhstan. Currently, when Turkey is selected as the default country and then Kazakhstan is chosen for the first time, the flag displayed is that of Turkey, instead of Kazakhstan. Subsequently selecting Kazakhstan again does display the correct Kazakhstan flag.

Steps to Reproduce:

1. Select Turkey as the default country.
2. Choose Kazakhstan from the country selection dropdown for the first time.
3. Observe that the flag displayed is that of Turkey, not Kazakhstan.
4. Now, select Kazakhstan again from the dropdown.
5. Notice that only on the second selection, the Kazakhstan flag is displayed correctly.

+90 is the country code for Turkey and +7 is the country code for Kazakistan. As seen in the photo, Turkey flag is shown when Kazakistan is chosen.
<img width="264" alt="image" src="https://github.com/viclafouch/mui-tel-input/assets/79802317/a49e4544-7089-4cce-b211-07dc89b1fb95">

**Comment by viclafouch** [comment]
Hello @mkontik 

https://github.com/viclafouch/mui-tel-input/assets/23353836/1c328f7f-ec39-4d0c-b08b-0e4871f6c28a

On my side, it's working fine. I select `Kazakhstan` from the country selection dropdown for the first time, I have correclty the `Kazakhstan` flag

**Comment by mkontik** [comment]
Hello Victor,

Thank you for your reply. 

We use the following code line and face the issue for +7 Kazakistan and just recognized +1 for US either. Country code for Turkey is +90. It seems when switching from two digit to one digit country we face the issue I send you.


const countries: MuiTelInputCountry[] = [
    "US",
    "BR",
    "DZ",
    "CN",
    "ID",
    "IN",
    "JP",
    "KZ",
    "HU",
    "MX",
    "NG",
    "PL",
    "RO",
    "TH",
    "TR",
    "VN",
  ];
<MuiTelInput
          variant="standard"
          size="small"
          id={item.id + "Id"}
          label={t(item.title)}
          value={getValues(item.id)}
          fullWidth
          onChange={(value: any) => {
            setValue(item.id, value, { shouldValidate: true });
          }}
          defaultCountry="TR"
          onlyCountries={countries}
          langOfCountryName={i18n.language}
        />

**Comment by viclafouch** [comment]
Yes because the phone library `libphonenumber-js` needs more info to be sure what country is it..

**Comment by mkontik** [comment]
We tried changing several parameters and fixed the issue. Thanks for the response.

**Comment by mkontik** [comment]
We tried changing several parameters and fixed the issue. Thanks for the response.
