### ISSUE TITLE
Phone Validation Issue with matchIsValidTel 

### ISSUE THREAD

**Issue by bliu13** [viclafouch/mui-tel-input#94]
I've tried using the provided validation function `matchIsValidTel` and it looks like it may not be behaving correctly. When I tried to validate a US number, it seemed to be validating one number short.

Correct US Number Format: +1 212 111 1111 (11 numbers)
Validation Only Accepts:       +1 212 111 111 (10 numbers)

```
import React from 'react'
import { MuiTelInput, matchIsValidTel } from 'mui-tel-input'

const MyComponent = () => {
  const [value, setValue] = React.useState('+12121111111')

  const handleChange = (newValue, info) => {
    console.log(matchIsValidTel(newValue)) // boolean
  }

  return (
    <MuiTelInput
            id="contact-telephone"
            inputProps={{ 'data-testid': 'contact-telephone' }}
            name="telephone"
            label="Telephone"
            fullWidth
            variant="outlined"
            defaultCountry="US"
            preferredCountries={['US']}
            forceCallingCode
            disableFormatting
            flagSize="medium"
            value={values.telephone}
            onChange={handleChange}
            error={!!errors.telephone}
            helperText={errors.telephone}
          />
  );
}
```

**Comment by viclafouch** [comment]
Hey 

This function comes from `libphonenumber-js`, so I think you should create an issue for this library, not `mui-tel-input`.

Victor

**Comment by bliu13** [comment]
Hi @viclafouch, I've just got around to test libphonenumber-js directly and according to the their documentation, the US phone numbers will say that it's not a valid phone number.
Here's the [original](https://libphonenumber.appspot.com/phonenumberparser?number=%2B12121111111) Google implementation behavior. I saw that there is another function that could be used: `isPossibleNumber()` and `isPossibleShortNumber()`. Is there a way to use these functions? It looks like they aren't re-exported in mui-tel-input.

**Comment by viclafouch** [comment]
Hello @bliu13 !

Good point, and you're right. But, in order to avoid increasing the size of the `mui-tel-input` package, I think that for a few rare cases like yours, it's better to install `libphonenumber-js` in your project and import the method yourself.

This will prevent all `mui-tel-input` users from seeing the package size increase for a function that is not useful.

What do you think ? :)
